#!/usr/bin/env python3
"""Build/update SYMBOL_INDEX.md for this repository.

Collects important symbols from source files:
- functions (primary)
- module exports (M.*)
- global assignments (vim.g)
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re


@dataclass(frozen=True)
class Symbol:
    kind: str
    file: str
    line: int
    name: str


FNL_FN_RE = re.compile(r"^\s*\(fn\s+([^\s\[]+)")
FNL_SET_M_RE = re.compile(r"^\s*\(set\s+M\.([^\s\)\]]+)")
FNL_SET_VIMG_RE = re.compile(r'^\s*\(set\s+\(\.\s+vim\.g\s+"([^"]+)"\)')

LUA_FN_RE = re.compile(r"^\s*(?:local\s+)?function\s+([A-Za-z0-9_\.:]+)\s*\(")
LUA_M_FN_RE = re.compile(r"^\s*M\.([A-Za-z0-9_]+)\s*=\s*function\s*\(")
LUA_M_SET_RE = re.compile(r"^\s*M\.([A-Za-z0-9_]+)\s*=")
LUA_VIMG_RE = re.compile(r'^\s*vim\.g(?:\["([^"]+)"\]|\.([A-Za-z0-9_]+))\s*=')


TARGET_DIRS = ("fnl", "plugin")
TARGET_SUFFIXES = (".fnl", ".lua")


def iter_source_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for rel in TARGET_DIRS:
        base = root / rel
        if not base.is_dir():
            continue
        for p in base.rglob("*"):
            if p.is_file() and p.suffix in TARGET_SUFFIXES:
                files.append(p)
    files.sort()
    return files


def collect_symbols(root: Path) -> list[Symbol]:
    out: list[Symbol] = []

    for path in iter_source_files(root):
        rel = path.relative_to(root).as_posix()
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError:
            continue

        for idx, line in enumerate(lines, start=1):
            m = FNL_FN_RE.search(line)
            if m:
                out.append(Symbol("function", rel, idx, m.group(1)))
                continue

            m = LUA_FN_RE.search(line)
            if m:
                out.append(Symbol("function", rel, idx, m.group(1)))
                continue

            m = LUA_M_FN_RE.search(line)
            if m:
                out.append(Symbol("function", rel, idx, f"M.{m.group(1)}"))
                continue

            m = FNL_SET_M_RE.search(line)
            if m:
                out.append(Symbol("export", rel, idx, f"M.{m.group(1)}"))
                continue

            m = LUA_M_SET_RE.search(line)
            if m:
                out.append(Symbol("export", rel, idx, f"M.{m.group(1)}"))
                continue

            m = FNL_SET_VIMG_RE.search(line)
            if m:
                out.append(Symbol("global", rel, idx, f"vim.g[\"{m.group(1)}\"]"))
                continue

            m = LUA_VIMG_RE.search(line)
            if m:
                key = m.group(1) or m.group(2)
                out.append(Symbol("global", rel, idx, f"vim.g.{key}"))

    out.sort(key=lambda s: (s.kind, s.file, s.line, s.name))
    return out


def write_index(root: Path, symbols: list[Symbol]) -> None:
    by_kind: dict[str, list[Symbol]] = {"function": [], "export": [], "global": []}
    for sym in symbols:
        by_kind.setdefault(sym.kind, []).append(sym)

    lines: list[str] = []
    lines.append("# Symbol Index")
    lines.append("")
    lines.append("Generated by `skills/symbol-index/scripts/update-symbol-index.py`.")
    lines.append("")

    def emit(kind: str, title: str) -> None:
        items = by_kind.get(kind, [])
        lines.append(f"## {title} ({len(items)})")
        lines.append("")
        if not items:
            lines.append("- _None_")
            lines.append("")
            return
        last_file = None
        for sym in items:
            if sym.file != last_file:
                lines.append(f"### `{sym.file}`")
                lines.append("")
                last_file = sym.file
            lines.append(f"- `{sym.name}` — line {sym.line}")
        lines.append("")

    emit("function", "Functions")
    emit("export", "Module Exports")
    emit("global", "Global Assignments")

    (root / "SYMBOL_INDEX.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    script = Path(__file__).resolve()
    root = script.parents[3]
    symbols = collect_symbols(root)
    write_index(root, symbols)
    print(f"[symbol-index] wrote {root / 'SYMBOL_INDEX.md'} ({len(symbols)} symbols)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
